### PR TITLE
Add fix for std::unary_function which is unavailable in VS2017 and newer

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

See https://github.com/RoboStack/ros-galactic/pull/57 for background information. /cc @wolfv

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
This is ready to go @conda-forge/graphicsmagick @wolfv

**Comment by wolfv** [comment]
Fix looks good to me. What do you think @ocefpaf?

**Comment by Tobias-Fischer** [comment]
I built this locally, and it fixed the issues for the RoboStack compilation.

/cc @bgruening @ocefpaf @wolfv

**Pull request merged**
